services:
  rewardhub:
    image: ghcr.io/yangmouren/rewardhub:latest
    container_name: rewardhub
    ports:
      - "9696:9696"
    environment:
      ADMIN_USERNAME: "${ADMIN_USERNAME:-}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD:-}"
    volumes:
      - ./points_data:/data
    restart: unless-stopped
